server:
  port: 8090

spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    username: LEARNUSER
    password: LEARNUSER
    url: jdbc:oracle:thin:@oracle-standard-container:1521:OraDoc

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.Oracle12cDialect
    hibernate:
      ddl-auto: update

  mvc:
    throw-exception-if-no-handler-found: true

management:
  security:
    enabled: false
  endpoint:
    shutdown:
      enabled: true
  port: 9000